'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { themes } from "./theme";
// import useStore from "./useStore";
import { useThemeStore } from "./store";
import { ThemeProvider } from '@emotion/react'

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentTheme = useThemeStore((state) => state.theme)
  // const currentTheme = useStore(useThemeStore, (state) => state.theme);

  // Function to get the theme style based on the theme value
  const getThemeStyle = (themeValue) => {
    return themes[themeValue] || themes.black; // Default to blackStyle if themeValue is not found
  };
  return (

    <ThemeProvider theme={getThemeStyle(currentTheme)}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ThemeProvider>
  );
}
